### ISSUE TITLE
除了特定屏幕外，输入框根本不会出现

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/you-draw-i-guess#2]
![O~HEEERHTI8}P~CZZ5~}NTS](https://user-images.githubusercontent.com/45287180/126898419-a54fe679-b7df-4617-b3a5-373eaaebfabf.png)

**Comment by Dianliang233** [comment]
所有元素都是硬编码宽高的，根本不 responsive

**Comment by XxLittleCxX** [comment]
@undefined-moe
